apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: podinfo
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: podinfo
  source:
    chart: podinfo/podinfo
    helm:
      values: |
        pushgateway:
          enabled: false
    repoURL: https://stefanprodan.github.io/podinfo
    targetRevision: 6.2.1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true